### ISSUE TITLE
Refactor and update global font family

### ISSUE THREAD

**Issue by francisl** [kids-first/kf-portal-ui#2760]
Current KF uses a custom font-family 'Montserrat'

It should be globally removed and use default system font.

```css

$fontMono : SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace;
pre { font-family:$fontMono };
code { font-family:$fontMono };

$fontBody : -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol";
body { font-family: $fontBody; }

}
```

- [ ] Remove all reference to Montserrat
- [ ] Remove custom font Montserrat
- [ ] Remove all reference for 'Open sans'
- [ ] Remove custom fon 'Open sans'
- [ ] Hardcoded value should be remove or use global variable in `src/styles/`
- [ ] Remove style from `.appContainer` Since it make sense to put it in the `body`
